### PR TITLE
Added a deployment depth .dat file for dy120 (05)

### PR DESCRIPTION
**Pull request by LewisDrysdale**

### CODE REVIEW

**Comment by lhoupert** [comment]
Good idea to update this deployment file! 
Are you planning to add the IB mooring at some point? or should I do it?

**Comment by LewisDrysdale** [comment]
I can do this, I just wasn't sure if this was to be done. I'm updating micrcat_calib_cruise.csv as well.

**Comment by lhoupert** [comment]
Perfect!
You will also see that because you created this pull request, all the changes you make on LewisDrysdale:dy120 are going to appear automatically here if you push them on your forked directory. Let me know when you are done with that and I can just merge your pull request.

**Comment by LewisDrysdale** [comment]
I have very little idea of what I am doing, but I think that may be it.

**Pull request merged**
